executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: source_file
    description: "%the-original-epub-file-to-be-translated%"
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        excludeAll: true
        filters:
          - name: EPUB
            extensions:
              - .epub
  - handle: translated_file
    description: "%the-saved-path-of-the-translated-epub-file-if-not-filled-in-spec%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: EPUE
            extensions:
              - .epub
    value:
    nullable: true
  - group: Translate
    collapsed: false
  - handle: language
    description: "%translation-target-language%"
    json_schema:
      enum:
        - zh-Hans
        - zh-Hant
        - en
        - fr
        - de
        - es
        - ru
        - it
        - pt
        - ja
        - ko
      ui:options:
        labels:
          - Simplified Chinese
          - Traditional Chinese
          - English
          - French
          - German
          - Spanish
          - Russian
          - Italian
          - Portuguese
          - Japanese
          - Korean
    value: zh-Hans
  - handle: write_mode
    description: '%how-is-the-translation-written-into-an-epub-file-is-it-append-to%'
    json_schema:
      enum:
        - append
        - replace
      ui:options:
        labels:
          - Append
          - Replace
    value: append
  - handle: prompt
    description: "%provide-llm-with-necessary-information-for-translating-books-for%"
    json_schema:
      type: string
      ui:widget: text
    value:
    nullable: true
  - group: LLM
    collapsed: true
  - handle: max_chunk_tokens
    description: "%the-entire-book-will-be-split-into-many-chunks-and-submitted-to%"
    json_schema:
      type: integer
    value: 2048
  - handle: threads
    description: "%the-number-of-threads-opened-at-the-same-time-to-initiate-reques%"
    json_schema:
      type: integer
      minimum: 1
    value: 4
  - handle: retry_times
    description: "%the-number-of-retries-after-an-llm-request-fails-is-limited-if-a%"
    json_schema:
      type: integer
      minimum: 1
    value: 5
  - handle: retry_interval_seconds
    description: "%how-long-in-seconds-after-a-failed-llm-request-starts-the-next-r%"
    json_schema:
      type: number
      minimum: 0
    value: 6.5
  - handle: model
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 0.5
      top_p: 0.5
      max_tokens: 4096
outputs_def:
  - handle: translated_file
    description: Translated EPUB file path.
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: EPUB
            extensions:
              - .epub
title: "%translate-a-book%"
description: "%use-llm-to-translate-epub-ebooks-the-translated-book-will-retain%"
